[env]
id = "./environments/self_prediction"

[env.args]
num_examples = 5

[trainer]
rollouts_per_example = 1
loss_fn = "importance_sampling"

[trainer.args]
max_new_tokens = 512

[model]
base_model = "meta-llama/Llama-3.2-1B"

[tinker]
api_key_env = "TINKER_API_KEY"
