[env]
id = "./environments/self_prediction"

[env.args]
num_examples = 5

[trainer]
rollouts_per_example = 1
loss_fn = "importance_sampling"

[trainer.args]
max_new_tokens = 512

[model]
base_model = "HuggingFaceTB/SmolLM2-360M-Instruct"

[tinker]
api_key_env = "TINKER_API_KEY"
