[env]
id = "./environments/self_prediction"

[trainer]
rollouts_per_example = 8
loss_fn = "importance_sampling"

  [trainer.args]
  max_new_tokens = 8096

[model]
base_model = "Qwen/Qwen3-30B-A3B"

[tinker]
api_key_env = "TINKER_API_KEY"
